apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ciscoworkload-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - namespaces
      - pods
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch