apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ciscoworkload-clusterrolebinding
subjects:
- kind: User
  name: ciscoworkload-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ciscoworkload-clusterrole
  apiGroup: rbac.authorization.k8s.io